### ISSUE TITLE
Failure when running npm run tsc

### ISSUE THREAD

**Issue by tstringer** [johnpapa/angular2-go#1]
I followed the steps on the readme:

 1. installed typescript live-server `npm install -g typescript live-server`
 2. cloned the repo to my local machine
 3. navigated to the repo with a console and ran `npm install`
 4. then attempted to run `npm run tsc` and that's when I got an error dump

The error stated at the root, the following:

*error     tsc -p src -w*

Specifically speaking, the console dumps the following:

```
error TS5023: Unknown option 'p'
Use the '--help' flag to see options.
error TS5023: Unknown option 'w'
Use the '--help' flag to see options.
error TS5007: Cannot resolve referenced file: 'src'.
```

**Comment by johnpapa** [comment]
what version of ts?

**Comment by fercreek** [comment]
@tstringer try this 
```
sudo apt-get install nodejs-legacy
```

**Comment by tstringer** [comment]
@johnpapa Please see below:

```
tsc -v
Version 1.0.3.0
```

**Comment by johnpapa** [comment]
run `npm install typescript -g` again. That should install the latest 1.5.3

If not, you need to look into why you have such an old TypeScript in your path

**Comment by kbdavis07** [comment]
Hi,

1. I am getting same error as tstringer, getting 404's for the source files.

2. I am getting 404 Errors for the node_modules
<script src="node_modules/traceur/bin/traceur-runtime.js"></script>
  <script src="node_modules/systemjs/dist/system.src.js"></script>
  <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
  <script src="node_modules/angular2/bundles/router.dev.js"></script>

I search my system after I installed node.js and these are not installed.

So I manually put them in:

<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>
  <script src="https://jspm.io/system@0.16.js"></script>
  <script src="https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js"></script>
  <script src="https://code.angularjs.org/2.0.0-alpha.28/router.dev.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

No more 404 errors, and no other errors but it just hangs there 

"loading"

Looked at the console log in Firefox.

Do not see any errors.

Is it just suppose to show "loading"?   :)

**Comment by johnpapa** [comment]
@kbdavis07 You shouldnt have to copy files to node_modules, so check your npm installation and setup.

OPen the dev tools, then refresh. Errors wont show unless the tools are open when you load it. 

Check network errors ... any 404s?

I'm "guessing" you have some npm or typescript version out of date, as does @tstringer

**Comment by johnpapa** [comment]
thanks for trying this :)

**Comment by kbdavis07** [comment]
John,

Did you know you can install a chat room for this repo?

https://gitter.im

Very easy to do :)

Would be useful.

**Comment by kbdavis07** [comment]
Hi John,

I do have 1.5.3  :)

**Comment by kbdavis07** [comment]
Error Log From NPM:


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'tsc' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'pretsc', 'tsc', 'posttsc' ]
5 info pretsc angular2-go@0.0.1
6 info tsc angular2-go@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info angular2-go@0.0.1 Failed to exec tsc script
9 verbose stack Error: angular2-go@0.0.1 tsc: `tsc -p src -w`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid angular2-go@0.0.1
11 verbose cwd C:\angular2-go-master
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tsc"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error angular2-go@0.0.1 tsc: `tsc -p src -w`
17 error Exit status 1
18 error Failed at the angular2-go@0.0.1 tsc script 'tsc -p src -w'.
18 error This is most likely a problem with the angular2-go package,
18 error not with npm itself.

18 error Tell the author that this fails on your system:
18 error     tsc -p src -w

18 error You can get their info via:
18 error     npm owner ls angular2-go
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by johnpapa** [comment]
so something is wrong with it resolving typescript. check your path.

when you say you have 1.5.3 are you seeing that when you run `tsc -v` ?

**Comment by tstringer** [comment]
@johnpapa Oddly enough, it doesn't:

```
tsc -v
Version 1.0.3.0

npm install typescript -g
... npm informational output (no errors) 
... removed for brevity

tsc -v
Version 1.0.3.0
```

**Comment by kbdavis07** [comment]
tsc -v  gives me 2.14.2

When I ran 

npm install typescript -g

node_modules\typescript\bin\tsservertypescript@1.5.3 
C:\Users\thecuddlyhoney\AppData\Roaming\npm\node_modules\typescript

**Comment by kbdavis07** [comment]
John,

If you can install the chat room from:

http://gitter.im

Like I have for my repos:

https://github.com/kbdavis07/BE-MVC

Very easy to add :)

**Comment by johnpapa** [comment]
I added it. 

there is no TS 2.14.2 ... thats oddly a popular npm version.

I think you both have some legacy TS in your paths.

**Comment by kbdavis07** [comment]
Chat room now at 

https://gitter.im/johnpapa/angular2-go#

:)

That will make things easier.

**Comment by kbdavis07** [comment]
I am there now

**Comment by kbdavis07** [comment]
Where are you John ?    :)

tstringer is there to waiting for you.

**Comment by kbdavis07** [comment]
In my case found solution:

Just run 

npm install

In the same directory that the app is located at.

C:\angular2-go-master

Console:

Cd /angular2-go-master npm install

That worked for me :)

**Comment by johnpapa** [comment]
where were you running it before?

**Comment by kbdavis07** [comment]
Same place, just for got to run

npm install

So the modules was not in the folder and this creating the 404 errors and etc.

**Comment by johnpapa** [comment]
ok, so we are all set?

**Comment by kbdavis07** [comment]
All set on my end.

It was a noobie issue not having used NPM before.

tstringer, on the other hand have some other issues, but it might be his local set up and not the project itself.

Thanks for all of your help, learn a lot, always wanted to learn to use NPM just never got around to it yet.

So many new things to learn with Asp.Net/ Microsoft products.

**Comment by tstringer** [comment]
So I stood up a VM and ran through the steps, no problem.  The version of typescript is not sticking (npm is definitely installing the right version, there's just another tsc that's taking precedence and I don't know from where yet.  My guess is it might be from my VS install perhaps, but that's just an assumption based off of where else typescript would have come from on my machine prior to this).

Thanks, John!

**Comment by Hallmanac** [comment]
Anyone who stumbles upon this, go to the gitter chat mentioned above ^ to see some other solutions to this issue with the Typescript compiler version. https://gitter.im/johnpapa/angular2-go#

**Comment by ianhorton** [comment]
Anyone stumbling across this, I had the same issue - I had 
'C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;' in my Environment Variables, removing it and installing via npm solved it for me.
