### ISSUE TITLE
replace deprecated api + tweak routing

### ISSUE THREAD

**Issue by Hotell** [johnpapa/angular2-go#14]
You are using deprecated `bind` Api which is now `provide` with slightly different syntax. 
Also in docs, there is info that Path Location strategy is used which doesn't reflect the code. 

IMO the hash strategy would be better to use with live-server and also the user won't get confused when he reloads the page on some active route + the Note section can get shorter :)

**Comment by johnpapa** [comment]
ah, i am in he process of switching to lite-server ... something that handles the html5 mode and injection of changes and syncing browsers via browser sync). so this is in process.

**Comment by Hotell** [comment]
sounds good!

**Comment by Hotell** [comment]
closing this 
https://github.com/johnpapa/angular2-go/pull/16
