### ISSUE TITLE
SystemJS to transpile TS files

### ISSUE THREAD

**Issue by antonmoiseev** [johnpapa/angular2-go#17]
Hi. I was looking for a very minimal Angular 2 + TypeScript + SystemJS setup that can be used to quickly create short examples. Really like your version! Minimal configuration, only one package manager :wink:, bundled Angular version, live reloading.

Have you considered using SystemJS for transpiling TypeScript code? I think it has a couple of advantages for this kind of app:

1. `src` directory doesn't get polluted with *.js and *.map files
2. No need to launch two terminals
3. live-server doesn't refresh browser twice for a single file change event

It will only require changing SystemJS configuration in `index.html` file:

```js
System.config({
  transpiler: 'typescript', // ask SystemJS to use typescript transpiler
  packages: {'app': {defaultExtension: 'ts'}}, // "ts" extension instead of "js"
  map: {'typescript': '../../node_modules/typescript/lib/typescript.js'} // explicitly set the path to tsc
});
```

**Comment by WayneRiesterer** [comment]
Hi @antonmoiseev . I tried this and still got transpiled files in the app folder. Is there something else that I have to do to prevent this?

**Comment by WayneRiesterer** [comment]
Cool starter app :)

Is there a way to remove /src that shows up in the browser address bar?

**Comment by antonmoiseev** [comment]
@WayneRiesterer You don't need to `npm run tsc` when SystemJS transpiles your code. `tsc` can be safely removed from the package.json scripts section.

The project uses `live-server` to host the app. It's launched in the root directory that becomes the web root of the server. Thus you need to use `/src` path to access the app. To get rid of it you have two options:

1. **Change the project layout - move everything from `src` directory one level up.** It might be tempting just to change the web root of the server. According to the [docs](https://github.com/tapio/live-server#usage-from-node) it can be done with the `root` param (seems like there is no a cli counterpart). But then `node_modules` won't be under your Web root and the app won't be able to load the dependencies. So changing the web root is not an option.

2. **Change the web server.** Looks like `live-server` doesn't support explicitly mapping paths to directories (like for example [browser-sync does](http://www.browsersync.io/docs/options/#option-server) and many others). So you may want to use some other web server for the project.

**Comment by antonybudianto** [comment]
@WayneRiesterer , take a look at my [starter](https://github.com/antonybudianto/angular2-starter) repo, I used the same `live-server` and you can use `root` option for removing the base directory

**Comment by renz45** [comment]
I changed the directory for where the ts files get compiled to by doing the following:

Add this to your `tsconfig.json`:
(Keep in mind I put all my code in a main app folder in the folder root.)
```
"outDir": "./dist/app"
```

Then change the systemJS config in your index.html to:

```
System.config({
  packages: {
    "dist/app": {       
      format: 'register',
      defaultExtension: 'js'
    }
  }
});
```

The first part tells the ts compiler to place compiled files in `/dist/app` while the second part reconfigures systemJS to look in that dist folder for files.

**Comment by johnpapa** [comment]
Transpiling in the browser is very slow once you get a larger app, as it happens all client side. 

`npm start` now is all you need, as it runs tsc and lite-server.

**Comment by xgqfrms-GitHub** [comment]
## config the typescript compiler path to 'app/dist' ???

## **root === ./**

> tsconfig.json  
```json
"outDir": "./app/dist"
or
"outDir": "app/dist"
``` 
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "outDir": "./dist"
    }
}
``` 
```js
/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      // app: 'app/dist',  &&  main: './dist/main.js',
      // Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/app/dist/dist/main.js(…)
      app: 'app',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        // index.html import path
        // Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/app/dist/main.js(…)
        // app: 'app/dist',  &&  main: './main.js',
        main: './dist/main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      }
    }
  });
})(this);
```
